name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: HiddenGuess/packages/frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies (workspace)
        run: |
          npm ci
          cd ../../contracts && npm ci
          cd ../frontend

      - name: Derive basePath for GitHub Pages
        id: base
        run: |
          REPO="${GITHUB_REPOSITORY#*/}"
          OWNER_REPO="${GITHUB_REPOSITORY}"
          OWNER="${OWNER_REPO%%/*}"
          if [[ "$REPO" == "${OWNER}.github.io" ]]; then
            echo "Using root basePath (empty)"
            echo "base_path=" >> $GITHUB_OUTPUT
          else
            echo "Using repo basePath: /$REPO"
            echo "base_path=/$REPO" >> $GITHUB_OUTPUT
          fi

      - name: Build static site
        env:
          BASE_PATH: ${{ steps.base.outputs.base_path }}
          NODE_ENV: production
        run: |
          npm run export
          # SPA fallback for GitHub Pages deep links
          cp -f out/index.html out/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: HiddenGuess/packages/frontend/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


